// AUTO-GENERATED by scripts/extract-hero-svg.mjs from design/Home.svg.
// Decorative layers only — chrome is rebuilt as HTML in Hero.jsx.
// Do not edit by hand — re-run `npm run extract:hero` instead.

export default function HeroBackdrop({ className = '', preserveAspectRatio = 'xMidYMid meet' }) {
  return (
    <svg
      className={className}
      viewBox="0 0 1440 1024"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      preserveAspectRatio={preserveAspectRatio}
      aria-hidden="true"
      focusable="false"
    >
      <g clipPath="url(#clip0_4_669)">
        <rect width="1440" height="1024" fill="#3A405A"/>
        <g opacity="0.08">
        <path opacity="0.25" d="M-1.5 51.5H1441.5M-1.5 98H1441.5M-1.5 152H1441.5M-1.5 199.5H1441.5M-1.5 250H1441.5M-1.5 303H1441.5M-1.5 352H1441.5M-1.5 401H1441.5M-1.5 450H1441.5M-1.5 500.5H1441.5M-1.5 551H1441.5M-1.5 601.5H1441.5M-1.5 650.5H1441.5M-1.5 702H1441.5M-1.5 752.5H1441.5M-1.5 801.5H1441.5M-1.5 850.5H1441.5M-1.5 899.5H1441.5M-1.5 950H1441.5M-1.5 999H1441.5" stroke="#FFF275" strokeWidth="0.5"/>
        <path opacity="0.25" d="M49 -1.5V1026.5M103 -1.5V1026.5M151 -1.5V1026.5M202.5 -1.5V1026.5M250 -1.5V1026.5M303 -1.5V1026.5M352 -1.5V1026.5M401 -1.5V1026.5M451.5 -1.5V1026.5M502 -1.5V1026.5M551 -1.5V1026.5M602.5 -1.5V1026.5M650 -1.5V1026.5M700.5 -1.5V1026.5M751 -1.5V1026.5M801.5 -1.5V1026.5M850.5 -1.5V1026.5M901 -1.5V1026.5M948.5 -1.5V1026.5M1001.5 -1.5V1026.5M1052 -1.5V1026.5M1101 -1.5V1026.5M1151.5 -1.5V1026.5M1199 -1.5V1026.5M1250.5 -1.5V1026.5M1301 -1.5V1026.5M1351.5 -1.5V1026.5M1400.5 -1.5V1026.5" stroke="#FFF275" strokeWidth="0.5"/>
        <circle opacity="0.45" cx="49" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="49" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="103" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="151" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="203" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="251" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="303" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="351" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="401" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="451" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="501" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="551" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="603" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="650" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="700" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="751" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="801" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="850" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="901" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="948" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1001" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1052" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1101" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1151" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1199" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1250" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1301" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1352" cy="999" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="52" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="98" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="152" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="200" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="250" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="303" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="352" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="401" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="450" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="500" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="551" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="602" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="650" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="702" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="752" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="802" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="851" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="900" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="950" r="3" fill="#D9D9D9"/>
        <circle opacity="0.45" cx="1401" cy="999" r="3" fill="#D9D9D9"/>
        </g>
        <g opacity="0.4" filter="url(#filter0_f_4_669)">
        <path d="M753.564 143.866L1107.72 266.928L1037.3 634.888L753.564 879.786L469.826 634.888L399.411 266.928L753.564 143.866ZM753.564 140.482L395.769 264.771L466.904 636.496L753.564 883.931L1040.22 636.496L1111.36 264.771L753.564 140.482Z" fill="#FFF275"/>
        <path d="M649.826 177.159C657.49 170.729 665.408 165.103 673.453 159.772C682.429 157.107 691.152 153.765 700.002 150.804L752.93 132.444L755.809 131.429C774.524 138.62 814.708 152.877 832.83 160.238C860.014 180.924 861.877 177.878 827.114 175.679C810.431 170.095 769.909 154.527 752.76 148.35L758.476 148.393L705.548 166.752C696.741 169.883 687.849 172.675 679.169 176.144C669.557 176.948 659.861 177.455 649.868 177.117L649.826 177.159Z" fill="#FF3C38"/>
        <path d="M556.67 714.42C546.973 710.655 537.869 706.213 528.978 701.56C521.949 694.791 514.412 688.572 507.171 682.015L463.262 643.265L461.102 641.361C457.122 620.082 447.553 574.648 444.038 553.834C444.631 543.935 445.182 534.078 446.537 524.01C451.618 532.767 455.894 541.693 460.213 550.619C462.5 559.926 464.066 569.402 466.014 578.794L477.15 635.227L474.44 630.531L518.35 669.282C525.717 675.67 532.831 682.354 540.452 688.488C546.168 696.737 551.716 705.198 556.67 714.378V714.42Z" fill="#FF3C38"/>
        <path d="M396.786 264.728L749.33 388.679L1111.36 264.728L755.682 883.636L396.786 264.728Z" stroke="#FFF275" strokeWidth="0.75" strokeMiterlimit="10"/>
        <path d="M950.458 714.419C955.412 705.282 960.916 696.821 966.675 688.529C974.254 682.395 981.367 675.711 988.777 669.323L1032.69 630.573L1029.98 635.269L1041.11 578.835C1043.06 569.444 1044.63 559.968 1046.91 550.661C1051.23 541.735 1055.51 532.808 1060.59 524.051C1061.95 534.077 1062.5 543.977 1063.09 553.876C1059.66 574.436 1050 620.293 1046.02 641.403L1043.86 643.306L999.956 682.057C992.715 688.572 985.178 694.833 978.149 701.601C969.257 706.255 960.154 710.697 950.458 714.462V714.419Z" fill="#FF3C38"/>
        <path d="M666.762 811.719C676.416 814.934 685.519 818.826 694.453 822.972C701.609 829.275 709.189 835.028 716.557 841.12L761.016 877.078L749.88 877.501C763.303 864.979 793.916 835.536 807.212 823.733C815.257 819.545 823.302 815.357 831.94 811.719C827.833 820.095 823.175 827.879 818.56 835.663C812.505 842.008 805.942 847.762 799.675 853.811C796.415 856.899 758.01 893.111 756.189 894.846L750.431 890.193L705.971 854.234C698.519 848.312 691.278 842.093 683.614 836.424C677.728 828.556 672.012 820.475 666.846 811.719H666.762Z" fill="#FF3C38"/>
        <path d="M421.175 388.679C415.628 379.034 410.928 369.219 406.567 359.362C404.958 348.955 402.629 338.675 400.681 328.311L388.486 266.336L387.089 259.144L394.033 256.733L452.805 236.215C462.628 232.916 472.325 229.151 482.275 226.189C492.903 225.132 503.489 224.032 514.371 223.693C505.649 230.208 496.672 235.961 487.695 241.715C478.041 245.564 468.133 248.653 458.394 252.164L399.622 272.681L405.127 263.078L417.322 325.054C419.439 335.376 421.175 345.74 423.631 356.02C423.334 366.808 422.7 377.68 421.218 388.679H421.175Z" fill="#FF3C38"/>
        <path d="M1086.97 388.679C1085.49 377.637 1084.85 366.808 1084.56 356.02C1087.01 345.783 1088.75 335.376 1090.87 325.054L1103.06 263.078L1108.57 272.681L1049.79 252.164C1040.01 248.653 1030.15 245.564 1020.49 241.715C1011.52 235.961 1002.54 230.208 993.817 223.693C1004.7 224.032 1015.28 225.089 1025.91 226.189C1035.86 229.193 1045.56 232.916 1055.38 236.215L1114.15 256.733L1121.1 259.144L1119.7 266.336L1107.51 328.311C1105.56 338.675 1103.23 348.955 1101.62 359.362C1097.22 369.219 1092.56 379.034 1087.01 388.679H1086.97Z" fill="#FF3C38"/>
        <path d="M754.071 67L762.539 140.44H745.602L754.071 67Z" fill="#FF3C38"/>
        <path d="M334.204 222.552L399.623 257.114L390.054 271.074L334.204 222.552Z" fill="#FF3C38"/>
        <path d="M1173.94 222.552L1118.09 271.074L1108.52 257.114L1173.94 222.552Z" fill="#FF3C38"/>
        <path d="M754.071 956.906L745.602 883.466H762.539L754.071 956.906Z" fill="#FF3C38"/>
        </g>
        <circle opacity="0.1" cx="754" cy="901" r="38" fill="#D9D9D9"/>
        <path d="M754.485 875.062L782.415 884.767L776.861 913.786L754.485 933.1L732.108 913.786L726.555 884.767L754.485 875.062ZM754.485 874.795L726.268 884.597L731.878 913.913L754.485 933.426L777.092 913.913L782.702 884.597L754.485 874.795Z" fill="#FF8C42"/>
        <path d="M746.303 877.688C746.908 877.18 747.532 876.737 748.167 876.316C748.874 876.106 749.562 875.843 750.26 875.609L754.434 874.161L754.661 874.081C756.137 874.648 759.306 875.773 760.736 876.353C762.88 877.985 763.026 877.744 760.285 877.571C758.969 877.13 755.773 875.903 754.421 875.416L754.872 875.419L750.698 876.867C750.003 877.114 749.302 877.334 748.617 877.608C747.859 877.671 747.095 877.711 746.307 877.684L746.303 877.688Z" fill="#78B3F5"/>
        <path d="M738.957 920.058C738.192 919.761 737.474 919.411 736.773 919.044C736.219 918.51 735.624 918.02 735.053 917.503L731.591 914.447L731.42 914.296C731.106 912.618 730.352 909.035 730.074 907.394C730.121 906.613 730.165 905.836 730.271 905.042C730.672 905.732 731.009 906.436 731.35 907.14C731.53 907.874 731.654 908.621 731.808 909.362L732.686 913.813L732.472 913.442L735.935 916.498C736.516 917.002 737.077 917.529 737.678 918.013C738.129 918.664 738.566 919.331 738.957 920.055V920.058Z" fill="#78B3F5"/>
        <path d="M726.348 884.594L754.151 894.369L782.702 884.594L754.652 933.403L726.348 884.594Z" stroke="#FF8C42" strokeWidth="0.75" strokeMiterlimit="10"/>
        <path d="M770.012 920.058C770.403 919.337 770.837 918.67 771.291 918.016C771.889 917.533 772.45 917.005 773.034 916.502L776.497 913.446L776.283 913.816L777.162 909.365C777.315 908.625 777.439 907.877 777.619 907.143C777.96 906.439 778.297 905.736 778.698 905.045C778.805 905.836 778.848 906.616 778.895 907.397C778.624 909.018 777.863 912.635 777.549 914.3L777.379 914.45L773.916 917.506C773.345 918.02 772.75 918.513 772.196 919.047C771.495 919.414 770.777 919.764 770.012 920.061V920.058Z" fill="#78B3F5"/>
        <path d="M747.639 927.732C748.401 927.985 749.118 928.292 749.823 928.619C750.387 929.116 750.985 929.57 751.566 930.05L755.072 932.886L754.194 932.919C755.253 931.932 757.667 929.61 758.716 928.679C759.35 928.349 759.985 928.018 760.666 927.732C760.342 928.392 759.975 929.006 759.611 929.62C759.133 930.12 758.615 930.574 758.121 931.051C757.864 931.295 754.835 934.15 754.692 934.287L754.238 933.92L750.731 931.084C750.144 930.617 749.573 930.127 748.968 929.68C748.504 929.059 748.053 928.422 747.646 927.732H747.639Z" fill="#78B3F5"/>
        <path d="M728.271 894.369C727.834 893.608 727.463 892.834 727.119 892.057C726.992 891.236 726.809 890.425 726.655 889.608L725.693 884.72L725.583 884.153L726.131 883.963L730.766 882.345C731.54 882.085 732.305 881.788 733.09 881.554C733.928 881.471 734.763 881.384 735.621 881.357C734.933 881.871 734.225 882.325 733.517 882.779C732.756 883.082 731.974 883.326 731.206 883.603L726.571 885.221L727.006 884.464L727.967 889.351C728.134 890.165 728.271 890.983 728.465 891.793C728.441 892.644 728.391 893.501 728.274 894.369H728.271Z" fill="#78B3F5"/>
        <path d="M780.778 894.369C780.661 893.498 780.611 892.644 780.588 891.793C780.781 890.986 780.918 890.165 781.085 889.351L782.047 884.464L782.481 885.221L777.846 883.603C777.075 883.326 776.297 883.082 775.535 882.779C774.827 882.325 774.12 881.871 773.432 881.357C774.29 881.384 775.125 881.468 775.963 881.554C776.748 881.791 777.512 882.085 778.287 882.345L782.922 883.963L783.47 884.153L783.359 884.72L782.398 889.608C782.244 890.425 782.06 891.236 781.934 892.057C781.586 892.834 781.219 893.608 780.781 894.369H780.778Z" fill="#78B3F5"/>
        <path d="M754.525 869L755.193 874.792H753.857L754.525 869Z" fill="#78B3F5"/>
        <path d="M721.412 881.267L726.571 883.993L725.817 885.094L721.412 881.267Z" fill="#78B3F5"/>
        <path d="M787.637 881.267L783.233 885.094L782.478 883.993L787.637 881.267Z" fill="#78B3F5"/>
        <path d="M754.525 939.182L753.857 933.39H755.193L754.525 939.182Z" fill="#78B3F5"/>
        <path opacity="0.2" d="M412.544 902.036C422.436 887.94 449.349 849.579 489.961 816.581" stroke="#FFF275" strokeWidth="3" strokeLinecap="round"/>
        <path opacity="0.2" d="M1089.16 902.036C1079.27 887.94 1052.36 849.579 1011.75 816.581" stroke="#FFF275" strokeWidth="3" strokeLinecap="round"/>
        <path opacity="0.2" d="M557.647 770.47C573.086 762.843 612.643 741.703 671.869 729.858" stroke="#FFF275" strokeWidth="3" strokeLinecap="round"/>
        <path opacity="0.2" d="M944.059 770.47C928.621 762.843 889.064 741.703 829.838 729.858" stroke="#FFF275" strokeWidth="3" strokeLinecap="round"/>
        <rect opacity="0.2" x="592.933" y="687.679" width="3" height="61.9408" transform="rotate(-16.4877 592.933 687.679)" fill="#FFF275"/>
        <rect opacity="0.2" x="577" y="631.851" width="3" height="61.9408" transform="rotate(-16.4877 577 631.851)" fill="#FFF275"/>
        <rect opacity="0.2" x="426.336" y="808.672" width="3" height="52.508" transform="rotate(-20.3966 426.336 808.672)" fill="#FFF275"/>
        <rect opacity="0.2" x="305" y="498.046" width="3" height="52.508" transform="rotate(-20.3966 305 498.046)" fill="#FFF275"/>
        <rect opacity="0.2" x="603.36" y="339.732" width="3" height="52.508" transform="rotate(0.261102 603.36 339.732)" fill="#FFF275"/>
        <rect opacity="0.2" x="894.239" y="360" width="3" height="52.508" transform="rotate(0.261102 894.239 360)" fill="#FFF275"/>
        <rect opacity="0.2" x="440.732" y="450" width="3" height="52.508" transform="rotate(4.07633 440.732 450)" fill="#FFF275"/>
        <rect opacity="0.2" x="385.362" y="715.628" width="3" height="62.895" transform="rotate(3.06368 385.362 715.628)" fill="#FFF275"/>
        <rect opacity="0.2" x="601.795" y="571.675" width="3" height="62.895" transform="rotate(23.7214 601.795 571.675)" fill="#FFF275"/>
        <rect opacity="0.2" x="965.022" y="654" width="3" height="62.895" transform="rotate(61.0248 965.022 654)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.769421 0.638741 0.638741 0.769421 864.308 637)" fill="#FFF275"/>
        <rect opacity="0.2" x="325.361" y="551" width="3" height="62.895" transform="rotate(3.06368 325.361 551)" fill="#FFF275"/>
        <rect opacity="0.2" x="603.73" y="396.465" width="3" height="62.895" transform="rotate(23.7214 603.73 396.465)" fill="#FFF275"/>
        <rect opacity="0.2" x="1038.3" y="368" width="3" height="62.895" transform="rotate(23.7214 1038.3 368)" fill="#FFF275"/>
        <rect opacity="0.2" x="849.302" y="463" width="3" height="62.895" transform="rotate(23.7214 849.302 463)" fill="#FFF275"/>
        <rect opacity="0.2" x="513.788" y="401" width="3" height="62.895" transform="rotate(1.62907 513.788 401)" fill="#FFF275"/>
        <rect opacity="0.2" x="960" y="536.952" width="3" height="62.895" transform="rotate(-18.4957 960 536.952)" fill="#FFF275"/>
        <rect opacity="0.2" x="861.788" y="574" width="3" height="62.895" transform="rotate(1.62907 861.788 574)" fill="#FFF275"/>
        <rect opacity="0.2" x="440" y="504.247" width="3" height="62.895" transform="rotate(-24.5612 440 504.247)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.53317 0.846008 0.846008 0.53317 331.599 744)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.797348 0.60352 0.60352 0.797348 541.48 579.257)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="128.981" transform="matrix(-0.53317 0.846008 0.846008 0.53317 468.69 561.765)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.53317 0.846008 0.846008 0.53317 322.599 617)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.797348 0.60352 0.60352 0.797348 577.862 457.247)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.797348 0.60352 0.60352 0.797348 826.392 522)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.797348 0.60352 0.60352 0.797348 516.392 466)" fill="#FFF275"/>
        <rect opacity="0.2" x="382" y="779.482" width="3" height="52.508" transform="rotate(-55.8293 382 779.482)" fill="#FFF275"/>
        <rect opacity="0.2" x="377" y="653.39" width="3" height="59.1945" transform="rotate(-7.46519 377 653.39)" fill="#FFF275"/>
        <rect opacity="0.2" x="615.927" y="510.489" width="3" height="59.1945" transform="rotate(13.1925 615.927 510.489)" fill="#FFF275"/>
        <rect opacity="0.2" x="974.51" y="476" width="3" height="59.1945" transform="rotate(13.1925 974.51 476)" fill="#FFF275"/>
        <rect opacity="0.2" x="979.51" y="596" width="3" height="59.1945" transform="rotate(13.1925 979.51 596)" fill="#FFF275"/>
        <rect opacity="0.2" x="319" y="682.39" width="3" height="59.1945" transform="rotate(-7.46519 319 682.39)" fill="#FFF275"/>
        <rect opacity="0.2" x="551.426" y="517.163" width="3" height="59.1945" transform="rotate(13.1925 551.426 517.163)" fill="#FFF275"/>
        <rect opacity="0.2" x="1010.82" y="427" width="3" height="59.1945" transform="rotate(37.2424 1010.82 427)" fill="#FFF275"/>
        <rect opacity="0.2" x="931.824" y="309" width="3" height="59.1945" transform="rotate(37.2424 931.824 309)" fill="#FFF275"/>
        <rect opacity="0.2" x="893.778" y="415" width="3" height="59.1945" transform="rotate(44.892 893.778 415)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="61.3225" transform="matrix(-0.958881 -0.283809 -0.283809 0.958881 906.281 690.272)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="61.3225" transform="matrix(-0.991426 -0.13067 -0.13067 0.991426 915.987 626.392)" fill="#FFF275"/>
        <rect opacity="0.2" x="611" y="747.885" width="3" height="170.312" transform="rotate(-38.9148 611 747.885)" fill="#D9D9D9"/>
        <rect opacity="0.2" x="448.721" y="859.685" width="3" height="268.38" transform="rotate(-78.6529 448.721 859.685)" fill="#D9D9D9"/>
        <rect opacity="0.2" width="3" height="268.38" transform="matrix(-0.196752 -0.980453 -0.980453 0.196752 1057.72 859.685)" fill="#D9D9D9"/>
        <rect opacity="0.2" width="3" height="163.359" transform="matrix(-0.800884 -0.598819 -0.598819 0.800884 888.225 748.796)" fill="#D9D9D9"/>
        <circle cx="612" cy="746" r="5" fill="#FF8C42"/>
        <circle cx="447" cy="857" r="5" fill="#FF8C42"/>
        <circle cx="1057" cy="858" r="5" fill="#FF8C42"/>
        <circle cx="888" cy="746" r="5" fill="#FF8C42"/>
        <circle cx="595" cy="687" r="5" fill="#78B3F5"/>
        <circle cx="578" cy="633" r="5" fill="#78B3F5"/>
        <circle cx="469" cy="562" r="5" fill="#78B3F5"/>
        <circle cx="439" cy="503" r="5" fill="#78B3F5"/>
        <circle cx="427" cy="808" r="5" fill="#78B3F5"/>
        <circle cx="330" cy="744" r="5" fill="#78B3F5"/>
        <circle cx="539.983" cy="578.693" r="5" transform="rotate(20.6577 539.983 578.693)" fill="#78B3F5"/>
        <circle cx="320" cy="682" r="5" fill="#78B3F5"/>
        <circle cx="552.499" cy="517.151" r="5" transform="rotate(20.6577 552.499 517.151)" fill="#78B3F5"/>
        <circle cx="387" cy="713" r="5" fill="#78B3F5"/>
        <circle cx="604.255" cy="569.794" r="5" transform="rotate(20.6577 604.255 569.794)" fill="#78B3F5"/>
        <circle cx="378" cy="652" r="5" fill="#78B3F5"/>
        <circle cx="617.353" cy="509.541" r="5" transform="rotate(20.6577 617.353 509.541)" fill="#78B3F5"/>
        <circle cx="323" cy="617" r="5" fill="#78B3F5"/>
        <circle cx="578.237" cy="457.389" r="5" transform="rotate(20.6577 578.237 457.389)" fill="#78B3F5"/>
        <circle cx="514.442" cy="465.442" r="5" transform="rotate(20.6577 514.442 465.442)" fill="#78B3F5"/>
        <circle cx="326" cy="551" r="5" fill="#78B3F5"/>
        <circle cx="604.328" cy="396.69" r="5" transform="rotate(20.6577 604.328 396.69)" fill="#78B3F5"/>
        <circle cx="604.442" cy="337.442" r="5" transform="rotate(20.6577 604.442 337.442)" fill="#78B3F5"/>
        <circle cx="515.442" cy="398.442" r="5" transform="rotate(20.6577 515.442 398.442)" fill="#78B3F5"/>
        <circle cx="441.442" cy="447.442" r="5" transform="rotate(20.6577 441.442 447.442)" fill="#78B3F5"/>
        <circle cx="304.442" cy="493.442" r="5" transform="rotate(20.6577 304.442 493.442)" fill="#78B3F5"/>
        <circle cx="383" cy="777" r="5" fill="#78B3F5"/>
        <rect opacity="0.2" width="3" height="52.508" transform="matrix(-0.937303 -0.348516 -0.348516 0.937303 1077.11 808.672)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="52.508" transform="matrix(-0.937303 -0.348516 -0.348516 0.937303 1198.45 498.046)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.998571 0.0534459 0.0534459 0.998571 1118.09 715.628)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="62.895" transform="matrix(-0.998571 0.0534459 0.0534459 0.998571 1178.09 551)" fill="#FFF275"/>
        <rect opacity="0.2" x="1171.85" y="744" width="3" height="62.895" transform="rotate(57.7801 1171.85 744)" fill="#FFF275"/>
        <rect opacity="0.2" x="1180.85" y="617" width="3" height="62.895" transform="rotate(57.7801 1180.85 617)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="52.508" transform="matrix(-0.56166 -0.827368 -0.827368 0.56166 1121.45 779.482)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="59.1945" transform="matrix(-0.991524 -0.129924 -0.129924 0.991524 1126.45 653.39)" fill="#FFF275"/>
        <rect opacity="0.2" width="3" height="59.1945" transform="matrix(-0.991524 -0.129924 -0.129924 0.991524 1184.45 682.39)" fill="#FFF275"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1081.45 803)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1178.45 739)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1188.45 677)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1121.45 708)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1130.45 647)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1185.45 612)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1182.45 546)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-0.935705 0.352784 0.352784 0.935705 1201.92 487)" fill="#78B3F5"/>
        <circle cx="5" cy="5" r="5" transform="matrix(-1 0 0 1 1125.45 772)" fill="#78B3F5"/>
        <circle cx="906" cy="687" r="5" fill="#78B3F5"/>
        <circle cx="966" cy="655" r="5" fill="#78B3F5"/>
        <circle cx="982" cy="596" r="5" fill="#78B3F5"/>
        <circle cx="961" cy="536" r="5" fill="#78B3F5"/>
        <circle cx="976" cy="476" r="5" fill="#78B3F5"/>
        <circle cx="1014" cy="427" r="5" fill="#78B3F5"/>
        <circle cx="1040" cy="368" r="5" fill="#78B3F5"/>
        <circle cx="915" cy="625" r="5" fill="#78B3F5"/>
        <circle cx="864" cy="574" r="5" fill="#78B3F5"/>
        <circle cx="896" cy="357" r="5" fill="#78B3F5"/>
        <circle cx="934" cy="309" r="5" fill="#78B3F5"/>
        <circle cx="825" cy="522" r="5" fill="#78B3F5"/>
        <circle cx="852" cy="459" r="5" fill="#78B3F5"/>
        <circle cx="894" cy="414" r="5" fill="#78B3F5"/>
        <circle cx="862" cy="637" r="5" fill="#78B3F5"/>
        <path d="M203.5 100H1243.5" stroke="#78B3F5" strokeWidth="0.25"/>
      </g>
      <defs>
      <filter id="filter0_f_4_669" x="290.904" y="23.7" width="926.334" height="976.506" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
      <feFlood floodOpacity="0" result="BackgroundImageFix"/>
      <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
      <feGaussianBlur stdDeviation="21.65" result="effect1_foregroundBlur_4_669"/>
      </filter>
      <clipPath id="clip0_4_669">
      <rect width="1440" height="1024" fill="white"/>
      </clipPath>
      </defs>
    </svg>
  );
}
